"""Build per-page CSS bundles from the UI modules (run before version-assets.py).

Source of truth: src/css/**/*.css (tokens, base, layout, components, screens, story modules)
plus the page → module load order in config/css-manifest.json.
Output: src/css/dist/<page>.css — one stylesheet per HTML entry, modules concatenated in
manifest order with a banner comment per module. Do not edit dist/ by hand.

    python3 scripts/build-css.py          # rebuild bundles
    python3 scripts/build-css.py --check  # exit 1 if bundles are stale or a module is unreferenced
"""
from pathlib import Path
import json
import sys

root = Path(__file__).resolve().parent.parent
css = root / 'src' / 'css'
manifest = json.loads((root / 'config' / 'css-manifest.json').read_text(encoding='utf8'))


def bundle(page: str) -> str:
    parts = [f'/* Generated by scripts/build-css.py for {page} — edit the modules under src/css/, not this file. */\n']
    for module in manifest['pages'][page]:
        source = css / module
        if not source.is_file():
            raise SystemExit(f'css-manifest: missing module {module} (page {page})')
        parts.append(f'\n/* ==== {module} ==== */\n' + source.read_text(encoding='utf8').rstrip('\n') + '\n')
    return ''.join(parts)


def unreferenced() -> list:
    used = {m for modules in manifest['pages'].values() for m in modules}
    found = {p.relative_to(css).as_posix() for p in css.rglob('*.css') if 'dist' not in p.relative_to(css).parts}
    return sorted(found - used)


def main(check: bool) -> int:
    orphans = unreferenced()
    if orphans:
        print('UNREFERENCED modules (add them to config/css-manifest.json):', *orphans, sep='\n  ')
        if check:
            return 1
    stale = []
    (css / 'dist').mkdir(exist_ok=True)
    for page, out in manifest['bundles'].items():
        target = root / out
        text = bundle(page)
        if check:
            if not target.is_file() or target.read_text(encoding='utf8') != text:
                stale.append(out)
        else:
            if not target.is_file() or target.read_text(encoding='utf8') != text:
                target.write_text(text, encoding='utf8')
                print('built', out, f'{len(text) / 1024:.0f} KB')
    if stale:
        print('STALE bundles (run python3 scripts/build-css.py):', *stale, sep='\n  ')
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main('--check' in sys.argv))
