"""Regenerate src/js/preload-manifest.js (run before version-assets.py).

core  = assets every session needs (cards, skins, character art, duel audio, UI frames in use).
story = every story asset referenced from code; the runtime derives exact per-node lists,
        this list is only the fallback order for background prefetch.
Fonts are left to the browser/service worker (unicode-range slices load on demand).
"""
from pathlib import Path
import hashlib, json, re

root = Path(__file__).resolve().parent.parent
EXT = {'.webp', '.png', '.jpg', '.jpeg', '.mp3', '.wav', '.ogg'}
CORE_DIRS = ['assets/cards', 'assets/skins', 'assets/environments', 'assets/icons',
             'assets/coins', 'assets/emblems', 'assets/characters', 'assets/audio/duel']

ref_re = re.compile(r'assets/[A-Za-z0-9_\-./]+\.(?:webp|png|jpe?g|mp3|wav|ogg)')
sources = list((root / 'src').rglob('*.js')) + list((root / 'src').rglob('*.css')) + list(root.glob('*.html'))
refs = set()
for f in sources:
    if f.name == 'preload-manifest.js':
        continue
    refs.update(ref_re.findall(f.read_text(encoding='utf8', errors='ignore')))
refs = {r for r in refs if (root / r).is_file()}

core = set()
for d in CORE_DIRS:
    for p in (root / d).rglob('*'):
        if p.is_file() and p.suffix.lower() in EXT:
            core.add(p.relative_to(root).as_posix())
core |= {r for r in refs if not r.startswith('assets/story/') and not r.startswith('assets/audio/story/') and not r.startswith('assets/fonts/')}
core = {c for c in core if '/frames/v1/' not in c or c in refs}
story = sorted(r for r in refs if (r.startswith('assets/story/') or r.startswith('assets/audio/story/')) and r not in core)

size = lambda items: sum((root / i).stat().st_size for i in items)
core = sorted(core)
version = hashlib.sha256('\n'.join(f'{i}:{(root / i).stat().st_size}' for i in core + story).encode()).hexdigest()[:10]
data = {'version': version, 'core': core, 'story': story, 'coreBytes': size(core), 'storyBytes': size(story)}
(root / 'src/js/preload-manifest.js').write_text(
    '/* Generated by scripts/build-preload-manifest.py — do not edit. */\nwindow.NDPreloadManifest=' + json.dumps(data, ensure_ascii=False, separators=(',', ':')) + ';\n')
print(f'core {len(core)} files {data["coreBytes"]/1e6:.1f} MB | story {len(story)} files {data["storyBytes"]/1e6:.1f} MB | v={version}')
